name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        cache-dependency-path: commons-nodejs/nest-config-aws/package-lock.json
        registry-url: 'https://registry.npmjs.org'
    
    - name: Install dependencies
      run: npm ci
      working-directory: commons-nodejs/nest-config-aws
    
    - name: Run quality checks
      run: npm run quality
      working-directory: commons-nodejs/nest-config-aws
    
    - name: Build package
      run: npm run build
      working-directory: commons-nodejs/nest-config-aws
    
    - name: Publish to npm
      run: npm publish
      working-directory: commons-nodejs/nest-config-aws
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}